### ISSUE TITLE
test BT-module

### ISSUE THREAD

**Issue by RisingOrange** [RisingOrange/Proximity-door-lock#4]

**Comment by sovcik** [comment]
1. create code to list all available BT devices 
1. create list/array of approved BT devices
1. turn on led when approved device is in the range (scan every 10 seconds)

**Comment by sovcik** [comment]
And document your prototype bradboard using Fritzing. see http://fritzing.org
Breadboard is fine, no need to create schematics and pcb view yet.
Once done, send me link to code & a PNG showing your bradboard in Fritzing (Fritzing can export to PNG)
